ARG REPOSITORY=docker.osdc.io
ARG BUILDER_TAG=3.1.0
FROM ${REPOSITORY}/ncigdc/amzn2023-builder:${BUILDER_TAG} AS builder

ARG VERSION

ENV SAMTOOLS_URL=https://github.com/samtools/samtools/releases/download/$VERSION/samtools-$VERSION.tar.bz2

RUN apk add \
	autoconf \
	automake \
	make \
	gcc \
	musl-dev \
	perl \
	zlib-dev \
	bzip2-dev \
	xz-dev \
	wget \
	libressl-dev \
	ncurses-dev

RUN wget $SAMTOOLS_URL \
	&& tar xf samtools-$VERSION.tar.bz2 \
	&& make -C samtools-$VERSION \
	&& make -C samtools-$VERSION install \
	&& rm -rf samtools-$VERSION

# For a multi-stage build

FROM ${REPOSITORY}/ncigdc/amzn2023:${BUILDER_TAG}

COPY --from=builder /usr/local/* /usr/local/
