ARG REPOSITORY=docker.osdc.io
ARG BUILDER_TAG=3.1.0
FROM ${REPOSITORY}/ncigdc/amzn2023-builder:${BUILDER_TAG} AS builder

ARG VERSION

ADD https://github.com/samtools/samtools/releases/download/$VERSION/samtools-$VERSION.tar.bz2 /samtools.tar.bz2

RUN tar -xvf /samtools.tar.bz2 \
      && cd /samtools-$VERSION \
      && ./configure \
      && make \
      && make install

RUN dnf install -y \
	autoconf \
	automake \
	make \
	gcc \
	perl \
	zlib-devel \
	bzip2-devel \
	xz-devel \
	wget \
	ncurses-devel

RUN wget $SAMTOOLS_URL \
	&& tar xf samtools-$VERSION.tar.bz2 \
	&& make -C samtools-$VERSION \
	&& make -C samtools-$VERSION install \
	&& rm -rf samtools-$VERSION

# For a multi-stage build

FROM ${REPOSITORY}/ncigdc/amzn2023:${BUILDER_TAG}

COPY --from=builder /usr/local/* /usr/local/
